version: '3.8'

services:
  mysqldb:
    image: mysql:8.3.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommercedb
    ports:
      - 3307:3306

  app: 
    build: .
    depends_on:
      - mysqldb
    links: 
      - mysqldb
    ports:
      - 3000:3000
