version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=DB
    ports:
      - "3307:3306"  # Puerto expuesto en tu máquina
    networks:
      - santos-app-network
    restart: always  # Asegura que el contenedor se reinicie si falla

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - MYSQLDB_HOST=db
      - MYSQLDB_USER=root
      - MYSQLDB_ROOT_PASSWORD=123456
      - MYSQLDB_DATABASE=DB
      - MYSQLDB_DOCKER_PORT=3306
      - JWT_SECRET=mysecretkey
    networks:
      - santos-app-network
    restart: always  # Asegura que el contenedor se reinicie si falla

networks:
  santos-app-network:
    external: true
